server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  datasource:
     #数据源基本配置
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://rm-bp1ro7q84u9k5o4wcko.mysql.rds.aliyuncs.com/0424?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
     username: yogovi
     password: Yogovi2018
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: order #order_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-order-consumer  #匹配后提供服务的路由地址
          predicates:
            - Path=/h/**         # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: localhost:8848
        group: DEV_GROUP
        namespace: 5440f5ff-35d5-4072-aee0-ca89d1316a66