server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
        namespace: 5440f5ff-35d5-4072-aee0-ca89d1316a66
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
      scg:
        fallback:
          #响应规则：重定向或者响应
          mode: 'response'
          #限流成功响应类型
          content-type: 'application/json'
          #响应体信息
          response-body: '网关限流成功'
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            namespace: 5440f5ff-35d5-4072-aee0-ca89d1316a66
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持


